// Auto-generated by `seal src/scripts/signature_generation/generate.luau`
// Do not edit manually — run the generator to regenerate.
//
// These constants expose typedef-derived function signatures so that
// `TableBuilder::with_function_and_signature` calls stay in sync with typedefs.

#![allow(dead_code)]

// archive.ar
pub const STD_ARCHIVE_AR_CREATE: &std::ffi::CStr = c"archive.ar.create() -> Archive";
pub const STD_ARCHIVE_AR_EXTRACT: &std::ffi::CStr = c"archive.ar.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_AR_LOAD: &std::ffi::CStr = c"archive.ar.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_AR_READFILE: &std::ffi::CStr = c"archive.ar.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_AR_WRITEFILE: &std::ffi::CStr = c"archive.ar.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive.deb
pub const STD_ARCHIVE_DEB_CREATE: &std::ffi::CStr = c"archive.deb.create() -> Archive";
pub const STD_ARCHIVE_DEB_EXTRACT: &std::ffi::CStr = c"archive.deb.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_DEB_LOAD: &std::ffi::CStr = c"archive.deb.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_DEB_READFILE: &std::ffi::CStr = c"archive.deb.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_DEB_WRITEFILE: &std::ffi::CStr = c"archive.deb.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive
pub const STD_ARCHIVE_CREATE: &std::ffi::CStr = c"archive.create() -> Archive";

// archive.sevenz
pub const STD_ARCHIVE_SEVENZ_CREATE: &std::ffi::CStr = c"archive.sevenz.create() -> Archive";
pub const STD_ARCHIVE_SEVENZ_EXTRACT: &std::ffi::CStr = c"archive.sevenz.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_SEVENZ_LOAD: &std::ffi::CStr = c"archive.sevenz.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_SEVENZ_READFILE: &std::ffi::CStr = c"archive.sevenz.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_SEVENZ_WRITEFILE: &std::ffi::CStr = c"archive.sevenz.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive.tar.gz
pub const STD_ARCHIVE_TAR_GZ_CREATE: &std::ffi::CStr = c"archive.tar.gz.create() -> Archive";
pub const STD_ARCHIVE_TAR_GZ_EXTRACT: &std::ffi::CStr = c"archive.tar.gz.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_TAR_GZ_LOAD: &std::ffi::CStr = c"archive.tar.gz.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_GZ_READFILE: &std::ffi::CStr = c"archive.tar.gz.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_GZ_WRITEFILE: &std::ffi::CStr = c"archive.tar.gz.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive.tar.uncompressed
pub const STD_ARCHIVE_TAR_UNCOMPRESSED_CREATE: &std::ffi::CStr = c"archive.tar.uncompressed.create() -> Archive";
pub const STD_ARCHIVE_TAR_UNCOMPRESSED_EXTRACT: &std::ffi::CStr = c"archive.tar.uncompressed.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_TAR_UNCOMPRESSED_LOAD: &std::ffi::CStr = c"archive.tar.uncompressed.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_UNCOMPRESSED_READFILE: &std::ffi::CStr = c"archive.tar.uncompressed.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_UNCOMPRESSED_WRITEFILE: &std::ffi::CStr = c"archive.tar.uncompressed.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive.tar.xz
pub const STD_ARCHIVE_TAR_XZ_CREATE: &std::ffi::CStr = c"archive.tar.xz.create() -> Archive";
pub const STD_ARCHIVE_TAR_XZ_EXTRACT: &std::ffi::CStr = c"archive.tar.xz.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_TAR_XZ_LOAD: &std::ffi::CStr = c"archive.tar.xz.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_XZ_READFILE: &std::ffi::CStr = c"archive.tar.xz.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_XZ_WRITEFILE: &std::ffi::CStr = c"archive.tar.xz.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive.tar.lz4
pub const STD_ARCHIVE_TAR_LZ4_CREATE: &std::ffi::CStr = c"archive.tar.lz4.create() -> Archive";
pub const STD_ARCHIVE_TAR_LZ4_EXTRACT: &std::ffi::CStr = c"archive.tar.lz4.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_TAR_LZ4_LOAD: &std::ffi::CStr = c"archive.tar.lz4.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_LZ4_READFILE: &std::ffi::CStr = c"archive.tar.lz4.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_LZ4_WRITEFILE: &std::ffi::CStr = c"archive.tar.lz4.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive.tar.bz2
pub const STD_ARCHIVE_TAR_BZ2_CREATE: &std::ffi::CStr = c"archive.tar.bz2.create() -> Archive";
pub const STD_ARCHIVE_TAR_BZ2_EXTRACT: &std::ffi::CStr = c"archive.tar.bz2.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_TAR_BZ2_LOAD: &std::ffi::CStr = c"archive.tar.bz2.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_BZ2_READFILE: &std::ffi::CStr = c"archive.tar.bz2.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_BZ2_WRITEFILE: &std::ffi::CStr = c"archive.tar.bz2.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive.tar.zst
pub const STD_ARCHIVE_TAR_ZST_CREATE: &std::ffi::CStr = c"archive.tar.zst.create() -> Archive";
pub const STD_ARCHIVE_TAR_ZST_EXTRACT: &std::ffi::CStr = c"archive.tar.zst.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_TAR_ZST_LOAD: &std::ffi::CStr = c"archive.tar.zst.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_ZST_READFILE: &std::ffi::CStr = c"archive.tar.zst.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_TAR_ZST_WRITEFILE: &std::ffi::CStr = c"archive.tar.zst.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// archive.zip
pub const STD_ARCHIVE_ZIP_CREATE: &std::ffi::CStr = c"archive.zip.create() -> Archive";
pub const STD_ARCHIVE_ZIP_EXTRACT: &std::ffi::CStr = c"archive.zip.extract(path: string, destination: string, options: ArchiveOptions?)";
pub const STD_ARCHIVE_ZIP_LOAD: &std::ffi::CStr = c"archive.zip.load(bytes: buffer, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_ZIP_READFILE: &std::ffi::CStr = c"archive.zip.readfile(path: string, options: ArchiveOptions?) -> Archive";
pub const STD_ARCHIVE_ZIP_WRITEFILE: &std::ffi::CStr = c"archive.zip.writefile(path: string, archive: Archive, options: ArchiveOptions?)";

// args
pub const STD_ARGS_COMMAND: &std::ffi::CStr = c"args.command(name: string, help: string) -> Command";
pub const STD_ARGS_DEFAULT: &std::ffi::CStr = c"args.default() -> Command";
pub const STD_ARGS_FLAG: &std::ffi::CStr = c"args.flag(name: string, help: string) -> Flag";
pub const STD_ARGS_LIST: &std::ffi::CStr = c"args.list(name: string, help: string) -> ArgList";
pub const STD_ARGS_NAMED: &std::ffi::CStr = c"args.named(name: string, help: string) -> Named";
pub const STD_ARGS_PARSE: &std::ffi::CStr = c"args.parse(program: string, tagline: string, info: ProgramInfo?) -> ArgParser";
pub const STD_ARGS_POSITIONAL: &std::ffi::CStr = c"args.positional(name: string, help: string) -> Positional";

// ArgParser
pub const STD_ARGS_ARG_PARSER_COMMANDS: &std::ffi::CStr = c"ArgParser:commands() -> Parsed";
pub const STD_ARGS_ARG_PARSER_SIMPLE: &std::ffi::CStr = c"ArgParser:simple() -> Parsed";

// Command
pub const STD_ARGS_COMMAND_ALIASES: &std::ffi::CStr = c"Command:aliases() -> Command";
pub const STD_ARGS_COMMAND_ARGS: &std::ffi::CStr = c"Command:args() -> Command";

// Parsed
pub const STD_ARGS_PARSED_EXPECT: &std::ffi::CStr = c"Parsed:expect(name: string, assertion: string?) -> T";
pub const STD_ARGS_PARSED_GET: &std::ffi::CStr = c"Parsed:get(name: string, default: T?) -> T?";
pub const STD_ARGS_PARSED_HELP: &std::ffi::CStr = c"Parsed:help() -> string";

// Positional
pub const STD_ARGS_POSITIONAL_DEFAULT: &std::ffi::CStr = c"Positional:default(any) -> Positional";
pub const STD_ARGS_POSITIONAL_OPTIONAL: &std::ffi::CStr = c"Positional:optional() -> Positional";
pub const STD_ARGS_POSITIONAL_VALIDATE: &std::ffi::CStr = c"Positional:validate(validator: Validator) -> Positional";

// Flag
pub const STD_ARGS_FLAG_ALIASES: &std::ffi::CStr = c"Flag:aliases() -> Flag";
pub const STD_ARGS_FLAG_DEFAULT: &std::ffi::CStr = c"Flag:default(boolean) -> Flag";

// Named
pub const STD_ARGS_NAMED_ALIASES: &std::ffi::CStr = c"Named:aliases() -> Named";
pub const STD_ARGS_NAMED_DEFAULT: &std::ffi::CStr = c"Named:default(any) -> Named";
pub const STD_ARGS_NAMED_REQUIRED: &std::ffi::CStr = c"Named:required() -> Named";
pub const STD_ARGS_NAMED_VALIDATE: &std::ffi::CStr = c"Named:validate(validator: Validator) -> Named";

// crypt.aes
pub const STD_CRYPT_AES_DECRYPT: &std::ffi::CStr = c"crypt.aes.decrypt(ciphertext: string, key: string) -> string";
pub const STD_CRYPT_AES_ENCRYPT: &std::ffi::CStr = c"crypt.aes.encrypt(plaintext: string, key: string) -> string";
pub const STD_CRYPT_AES_GENERATEKEY: &std::ffi::CStr = c"crypt.aes.generatekey() -> string";

// crypt.hash
pub const STD_CRYPT_HASH_SHA2: &std::ffi::CStr = c"crypt.hash.sha2(plaintext: string) -> buffer";

// crypt.password
pub const STD_CRYPT_PASSWORD_HASH: &std::ffi::CStr = c"crypt.password.hash(raw_password: string) -> HashedPassword";
pub const STD_CRYPT_PASSWORD_VERIFY: &std::ffi::CStr = c"crypt.password.verify(verify_options: PasswordVerifyOptions) -> boolean";

// crypt.rsa
pub const STD_CRYPT_RSA_DECRYPT: &std::ffi::CStr = c"crypt.rsa.decrypt(ciphertext: string, private_key: string) -> string";
pub const STD_CRYPT_RSA_ENCRYPT: &std::ffi::CStr = c"crypt.rsa.encrypt(plaintext: string, public_key: string) -> string";
pub const STD_CRYPT_RSA_GENERATEKEYS: &std::ffi::CStr = c"crypt.rsa.generatekeys() -> RsaKeys";

// env
pub const STD_ENV_CWD: &std::ffi::CStr = c"env.cwd() -> string";

// env.vars
pub const STD_ENV_VARS_ALL: &std::ffi::CStr = c"env.vars.all() -> { [string]: string }";
pub const STD_ENV_VARS_FLAG: &std::ffi::CStr = c"env.vars.flag(name: string, default: boolean) -> boolean";
pub const STD_ENV_VARS_GET: &std::ffi::CStr = c"env.vars.get(key: string) -> string?";
pub const STD_ENV_VARS_LOAD: &std::ffi::CStr = c"env.vars.load(path: string, override: boolean?)";
pub const STD_ENV_VARS_SET: &std::ffi::CStr = c"env.vars.set(key: string, value: string)";
pub const STD_ENV_VARS_UNSET: &std::ffi::CStr = c"env.vars.unset(key: string)";
pub const STD_ENV_VARS_VALIDATE: &std::ffi::CStr = c"env.vars.validate(key: string, f: (value: string?) -> T) -> T";

// err
pub const STD_ERR_EXTRACT: &std::ffi::CStr = c"err.extract(err: error) -> { message: string, traceback: string? }";
pub const STD_ERR_FORMAT: &std::ffi::CStr = c"err.format(err: error) -> string";
pub const STD_ERR_MESSAGE: &std::ffi::CStr = c"err.message(string) -> error";
pub const STD_ERR_THROW: &std::ffi::CStr = c"err.throw(err: error) -> never";
pub const STD_ERR_TRACEBACK: &std::ffi::CStr = c"err.traceback(message: string?, level: number?) -> string";
pub const STD_ERR_WRAP: &std::ffi::CStr = c"err.wrap(message: string) -> error";

// TreeBuilder
pub const STD_FS_TREE_BUILDER_WITH_FILE: &std::ffi::CStr = c"TreeBuilder:with_file(name: string, content: string) -> TreeBuilder";
pub const STD_FS_TREE_BUILDER_WITH_TREE: &std::ffi::CStr = c"TreeBuilder:with_tree(name: string, builder: TreeBuilder) -> TreeBuilder";

// FileEntry
pub const STD_FS_FILE_ENTRY_APPEND: &std::ffi::CStr = c"FileEntry:append(content: buffer | string)";
pub const STD_FS_FILE_ENTRY_COPY_TO: &std::ffi::CStr = c"FileEntry:copy_to(to: string)";
pub const STD_FS_FILE_ENTRY_IS_VALID_UTF8: &std::ffi::CStr = c"FileEntry:is_valid_utf8() -> boolean";
pub const STD_FS_FILE_ENTRY_METADATA: &std::ffi::CStr = c"FileEntry:metadata() -> FsMetadata";
pub const STD_FS_FILE_ENTRY_MOVE_TO: &std::ffi::CStr = c"FileEntry:move_to(to: string)";
pub const STD_FS_FILE_ENTRY_READ: &std::ffi::CStr = c"FileEntry:read() -> string";
pub const STD_FS_FILE_ENTRY_READBYTES: &std::ffi::CStr = c"FileEntry:readbytes(file_offset: number?, count: number?, target_buffer: buffer?, buffer_offset: number?) -> buffer";
pub const STD_FS_FILE_ENTRY_READLINES: &std::ffi::CStr = c"FileEntry:readlines() -> () -> (number, string)";
pub const STD_FS_FILE_ENTRY_REMOVE: &std::ffi::CStr = c"FileEntry:remove()";
pub const STD_FS_FILE_ENTRY_RENAME: &std::ffi::CStr = c"FileEntry:rename(name: string)";
pub const STD_FS_FILE_ENTRY_SIZE: &std::ffi::CStr = c"FileEntry:size() -> number";

// DirectoryEntry
pub const STD_FS_DIRECTORY_ENTRY_ADD_FILE: &std::ffi::CStr = c"DirectoryEntry:add_file(name: string, content: string | buffer) -> DirectoryEntry";
pub const STD_FS_DIRECTORY_ENTRY_ADD_TREE: &std::ffi::CStr = c"DirectoryEntry:add_tree(name: string, builder: TreeBuilder) -> DirectoryEntry";
pub const STD_FS_DIRECTORY_ENTRY_COPY_TO: &std::ffi::CStr = c"DirectoryEntry:copy_to(to: string)";
pub const STD_FS_DIRECTORY_ENTRY_ENTRIES: &std::ffi::CStr = c"DirectoryEntry:entries() -> { [string]: Entry }";
pub const STD_FS_DIRECTORY_ENTRY_EXPECT_DIR: &std::ffi::CStr = c"DirectoryEntry:expect_dir(name: string) -> DirectoryEntry";
pub const STD_FS_DIRECTORY_ENTRY_EXPECT_FILE: &std::ffi::CStr = c"DirectoryEntry:expect_file(name: string) -> FileEntry";
pub const STD_FS_DIRECTORY_ENTRY_FIND: &std::ffi::CStr = c"DirectoryEntry:find(name: string, options: { follow_symlinks: boolean?, error_if_permission_denied: boolean? }?) -> FindResult";
pub const STD_FS_DIRECTORY_ENTRY_JOIN: &std::ffi::CStr = c"DirectoryEntry:join() -> string";
pub const STD_FS_DIRECTORY_ENTRY_LIST: &std::ffi::CStr = c"DirectoryEntry:list(recursive: boolean?, filter: (path: string) -> boolean?) -> { [number]: string }";
pub const STD_FS_DIRECTORY_ENTRY_METADATA: &std::ffi::CStr = c"DirectoryEntry:metadata() -> FsMetadata";
pub const STD_FS_DIRECTORY_ENTRY_MOVE_TO: &std::ffi::CStr = c"DirectoryEntry:move_to(to: string)";
pub const STD_FS_DIRECTORY_ENTRY_REMOVE: &std::ffi::CStr = c"DirectoryEntry:remove()";
pub const STD_FS_DIRECTORY_ENTRY_RENAME: &std::ffi::CStr = c"DirectoryEntry:rename(name: string)";

// FindResult
pub const STD_FS_FIND_RESULT_EXISTS: &std::ffi::CStr = c"FindResult:exists() -> boolean";
pub const STD_FS_FIND_RESULT_TRY_DIR: &std::ffi::CStr = c"FindResult:try_dir() -> DirectoryEntry?";
pub const STD_FS_FIND_RESULT_TRY_FILE: &std::ffi::CStr = c"FindResult:try_file() -> FileEntry?";
pub const STD_FS_FIND_RESULT_UNWRAP_DIR: &std::ffi::CStr = c"FindResult:unwrap_dir() -> DirectoryEntry";
pub const STD_FS_FIND_RESULT_UNWRAP_FILE: &std::ffi::CStr = c"FindResult:unwrap_file() -> FileEntry";

// fs.dir
pub const STD_FS_DIR_BUILD: &std::ffi::CStr = c"fs.dir.build(name: string, tree: DirectoryTree) -> DirectoryBuilder";
pub const STD_FS_DIR_CREATE: &std::ffi::CStr = c"fs.dir.create(path: string) -> DirectoryEntry";
pub const STD_FS_DIR_CWD: &std::ffi::CStr = c"fs.dir.cwd() -> DirectoryEntry";
pub const STD_FS_DIR_ENSURE: &std::ffi::CStr = c"fs.dir.ensure(path: string, create_missing: boolean?) -> DirectoryEntry";
pub const STD_FS_DIR_FROM: &std::ffi::CStr = c"fs.dir.from(path: string) -> DirectoryEntry";
pub const STD_FS_DIR_HOME: &std::ffi::CStr = c"fs.dir.home() -> DirectoryEntry";
pub const STD_FS_DIR_PROJECT: &std::ffi::CStr = c"fs.dir.project(n: number?) -> DirectoryEntry";
pub const STD_FS_DIR_TRY_REMOVE: &std::ffi::CStr = c"fs.dir.try_remove(path: string) -> (boolean, \"Ok\" | \"PermissionDenied\" | \"NotFound\" | \"NotADirectory\" | \"Other\", string?)";

// fs.file
pub const STD_FS_FILE_BUILD: &std::ffi::CStr = c"fs.file.build(name: string, content: string) -> FileBuilder";
pub const STD_FS_FILE_CREATE: &std::ffi::CStr = c"fs.file.create(path: string) -> FileEntry";
pub const STD_FS_FILE_FROM: &std::ffi::CStr = c"fs.file.from(path: string) -> FileEntry";
pub const STD_FS_FILE_TRY_READ: &std::ffi::CStr = c"fs.file.try_read(path: string) -> (string?, \"Ok\" | \"NotFound\" | \"PermissionDenied\")";
pub const STD_FS_FILE_TRY_READBYTES: &std::ffi::CStr = c"fs.file.try_readbytes(path: string, file_offset: number?, count: number?, target_buffer: buffer?, buffer_offset: number?) -> (buffer?, \"Ok\" | \"NotFound\" | \"PermissionDenied\")";
pub const STD_FS_FILE_TRY_REMOVE: &std::ffi::CStr = c"fs.file.try_remove(path: string) -> (boolean, \"Ok\" | \"PermissionDenied\" | \"NotFound\" | \"IsADirectory\")";
pub const STD_FS_FILE_TRY_WRITE: &std::ffi::CStr = c"fs.file.try_write(path: string, content: string | buffer) -> (boolean, \"Ok\" | \"PermissionDenied\")";

// fs.filesize
pub const STD_FS_FILESIZE_BYTES: &std::ffi::CStr = c"fs.filesize.bytes(count: number) -> FileSize";
pub const STD_FS_FILESIZE_GIGABYTES: &std::ffi::CStr = c"fs.filesize.gigabytes(count: number) -> FileSize";
pub const STD_FS_FILESIZE_KILOBYTES: &std::ffi::CStr = c"fs.filesize.kilobytes(count: number) -> FileSize";
pub const STD_FS_FILESIZE_MEGABYTES: &std::ffi::CStr = c"fs.filesize.megabytes(count: number) -> FileSize";
pub const STD_FS_FILESIZE_TERABYTES: &std::ffi::CStr = c"fs.filesize.terabytes(count: number) -> FileSize";

// fs
pub const STD_FS_COPY: &std::ffi::CStr = c"fs.copy(source: string, destination: string)";
pub const STD_FS_ENTRIES: &std::ffi::CStr = c"fs.entries(path: string) -> { [string]: Entry }";
pub const STD_FS_FIND: &std::ffi::CStr = c"fs.find(path: string, options: { follow_symlinks: boolean?, error_if_permission_denied: boolean? }?) -> FindResult";
pub const STD_FS_IS: &std::ffi::CStr = c"fs.is(path: string) -> PathIs";
pub const STD_FS_LISTDIR: &std::ffi::CStr = c"fs.listdir(path: string, recursive: boolean?, filter: (path: string) -> boolean?) -> { [number]: string }";
pub const STD_FS_MAKEDIR: &std::ffi::CStr = c"fs.makedir(path: string, options: { create_missing: boolean?, error_if_exists: boolean? }?) -> boolean";
pub const STD_FS_MOVE: &std::ffi::CStr = c"fs.move(from: string, to: string)";
pub const STD_FS_READBYTES: &std::ffi::CStr = c"fs.readbytes(path: string, file_offset: number?, count: number?, target_buffer: buffer?, buffer_offset: number?) -> buffer";
pub const STD_FS_READFILE: &std::ffi::CStr = c"fs.readfile(path: string) -> string";
pub const STD_FS_READLINES: &std::ffi::CStr = c"fs.readlines(path: string) -> () -> (number, string)";
pub const STD_FS_READLINK: &std::ffi::CStr = c"fs.readlink(symlink: string) -> string";
pub const STD_FS_READTREE: &std::ffi::CStr = c"fs.readtree(path: string) -> DirectoryTree";
pub const STD_FS_REMOVEFILE: &std::ffi::CStr = c"fs.removefile(path: string)";
pub const STD_FS_REMOVETREE: &std::ffi::CStr = c"fs.removetree(path: string)";
pub const STD_FS_SYMLINK: &std::ffi::CStr = c"fs.symlink(target: string, link: string) -> boolean";
pub const STD_FS_TREE: &std::ffi::CStr = c"fs.tree() -> TreeBuilder";
pub const STD_FS_UNSYMLINK: &std::ffi::CStr = c"fs.unsymlink(link: string) -> boolean";
pub const STD_FS_WATCH: &std::ffi::CStr = c"fs.watch(paths: string | { [number]: string }, options: WatchOptions?) -> () -> (WatchEventCategory, WatchEventInfo)";
pub const STD_FS_WRITEFILE: &std::ffi::CStr = c"fs.writefile(path: string, content: string | buffer)";
pub const STD_FS_WRITETREE: &std::ffi::CStr = c"fs.writetree(path: string, tree: TreeBuilder | DirectoryTree)";

// fs.path
pub const STD_FS_PATH_ABSOLUTIZE: &std::ffi::CStr = c"fs.path.absolutize(path: string) -> string";
pub const STD_FS_PATH_CANONICALIZE: &std::ffi::CStr = c"fs.path.canonicalize(path: string) -> string";
pub const STD_FS_PATH_CHILD: &std::ffi::CStr = c"fs.path.child(path: string) -> string?";
pub const STD_FS_PATH_CWD: &std::ffi::CStr = c"fs.path.cwd() -> string";
pub const STD_FS_PATH_EXISTS: &std::ffi::CStr = c"fs.path.exists(path: string) -> boolean";
pub const STD_FS_PATH_HOME: &std::ffi::CStr = c"fs.path.home() -> string";
pub const STD_FS_PATH_JOIN: &std::ffi::CStr = c"fs.path.join() -> string";
pub const STD_FS_PATH_NORMALIZE: &std::ffi::CStr = c"fs.path.normalize(path: string) -> string";
pub const STD_FS_PATH_PARENT: &std::ffi::CStr = c"fs.path.parent(path: string, n: number?) -> string?";
pub const STD_FS_PATH_PROJECT: &std::ffi::CStr = c"fs.path.project(n: number?, script_path: string?) -> string?";

// io.colors
pub const STD_IO_COLORS_BLACK: &std::ffi::CStr = c"io.colors.black(text: string) -> string";
pub const STD_IO_COLORS_BLUE: &std::ffi::CStr = c"io.colors.blue(text: string) -> string";
pub const STD_IO_COLORS_CYAN: &std::ffi::CStr = c"io.colors.cyan(text: string) -> string";
pub const STD_IO_COLORS_ENABLED: &std::ffi::CStr = c"io.colors.enabled() -> boolean";
pub const STD_IO_COLORS_GREEN: &std::ffi::CStr = c"io.colors.green(text: string) -> string";
pub const STD_IO_COLORS_MAGENTA: &std::ffi::CStr = c"io.colors.magenta(text: string) -> string";
pub const STD_IO_COLORS_OVERRIDE: &std::ffi::CStr = c"io.colors.override(enabled: boolean)";
pub const STD_IO_COLORS_RED: &std::ffi::CStr = c"io.colors.red(text: string) -> string";
pub const STD_IO_COLORS_RGB: &std::ffi::CStr = c"io.colors.rgb(rgb: vector, text: string?) -> string";
pub const STD_IO_COLORS_WHITE: &std::ffi::CStr = c"io.colors.white(text: string) -> string";
pub const STD_IO_COLORS_YELLOW: &std::ffi::CStr = c"io.colors.yellow(text: string) -> string";

// io.colors.bold
pub const STD_IO_COLORS_BOLD_BLACK: &std::ffi::CStr = c"io.colors.bold.black(text: string) -> string";
pub const STD_IO_COLORS_BOLD_BLUE: &std::ffi::CStr = c"io.colors.bold.blue(text: string) -> string";
pub const STD_IO_COLORS_BOLD_CYAN: &std::ffi::CStr = c"io.colors.bold.cyan(text: string) -> string";
pub const STD_IO_COLORS_BOLD_GREEN: &std::ffi::CStr = c"io.colors.bold.green(text: string) -> string";
pub const STD_IO_COLORS_BOLD_MAGENTA: &std::ffi::CStr = c"io.colors.bold.magenta(text: string) -> string";
pub const STD_IO_COLORS_BOLD_RED: &std::ffi::CStr = c"io.colors.bold.red(text: string) -> string";
pub const STD_IO_COLORS_BOLD_WHITE: &std::ffi::CStr = c"io.colors.bold.white(text: string) -> string";
pub const STD_IO_COLORS_BOLD_YELLOW: &std::ffi::CStr = c"io.colors.bold.yellow(text: string) -> string";

// io.colors.style
pub const STD_IO_COLORS_STYLE_BOLD: &std::ffi::CStr = c"io.colors.style.bold(text: string) -> string";
pub const STD_IO_COLORS_STYLE_DIM: &std::ffi::CStr = c"io.colors.style.dim(text: string) -> string";
pub const STD_IO_COLORS_STYLE_UNDERLINE: &std::ffi::CStr = c"io.colors.style.underline(text: string) -> string";

// io.format
pub const STD_IO_FORMAT_DEBUG: &std::ffi::CStr = c"io.format.debug(item: unknown) -> string";
pub const STD_IO_FORMAT_DEFAULTS: &std::ffi::CStr = c"io.format.defaults(options: FormatOptions?)";
pub const STD_IO_FORMAT_HEXDUMP: &std::ffi::CStr = c"io.format.hexdump(data: string | buffer) -> string";
pub const STD_IO_FORMAT_PRETTY: &std::ffi::CStr = c"io.format.pretty(item: unknown, options: FormatOptions?, current_depth: number?) -> string";
pub const STD_IO_FORMAT_SIMPLE: &std::ffi::CStr = c"io.format.simple(item: unknown) -> string";
pub const STD_IO_FORMAT_UNCOLOR: &std::ffi::CStr = c"io.format.uncolor(s: string) -> string";

// io.input
pub const STD_IO_INPUT_EDITLINE: &std::ffi::CStr = c"io.input.editline(prompt: string, left: string, right: string?) -> string | interrupt | error";
pub const STD_IO_INPUT_GET: &std::ffi::CStr = c"io.input.get(raw_prompt: string) -> string";
pub const STD_IO_INPUT_INTERRUPT: &std::ffi::CStr = c"io.input.interrupt(key: \"CtrlC\" | \"CtrlD\") -> interrupt";
pub const STD_IO_INPUT_RAWLINE: &std::ffi::CStr = c"io.input.rawline(prompt: string?) -> string";
pub const STD_IO_INPUT_READ: &std::ffi::CStr = c"io.input.read(options: InputReadOptions?) -> (string?, boolean)";
pub const STD_IO_INPUT_READLINE: &std::ffi::CStr = c"io.input.readline(prompt: string) -> string | interrupt | error";

// io.output
pub const STD_IO_OUTPUT_CLEAR: &std::ffi::CStr = c"io.output.clear()";
pub const STD_IO_OUTPUT_EWRITE: &std::ffi::CStr = c"io.output.ewrite(contents: string | buffer) -> error?";
pub const STD_IO_OUTPUT_EWRITELN: &std::ffi::CStr = c"io.output.ewriteln(contents: string | buffer) -> error?";
pub const STD_IO_OUTPUT_WRITE: &std::ffi::CStr = c"io.output.write(contents: string | buffer) -> error?";
pub const STD_IO_OUTPUT_WRITELN: &std::ffi::CStr = c"io.output.writeln(contents: string | buffer) -> error?";

// io.prompt
pub const STD_IO_PROMPT_CONFIRM: &std::ffi::CStr = c"io.prompt.confirm(message: string, default: boolean?) -> boolean";
pub const STD_IO_PROMPT_EDIT: &std::ffi::CStr = c"io.prompt.edit(prompt: string, left: string, right: string?) -> string";
pub const STD_IO_PROMPT_PASSWORD: &std::ffi::CStr = c"io.prompt.password(message: string, style: \"Hidden\" | \"*\" | nil) -> string";
pub const STD_IO_PROMPT_PICK: &std::ffi::CStr = c"io.prompt.pick(message: string, options: { [number]: string }, default: number?) -> number";
pub const STD_IO_PROMPT_TEXT: &std::ffi::CStr = c"io.prompt.text(message: string) -> string";
pub const STD_IO_PROMPT_VALIDATE: &std::ffi::CStr = c"io.prompt.validate(message: string, v: (response: string) -> true | string) -> string";

// json
pub const STD_JSON_ARRAY: &std::ffi::CStr = c"json.array(t: { [number]: T }?) -> { [number]: T }";
pub const STD_JSON_DECODE: &std::ffi::CStr = c"json.decode(json: string) -> JsonData";
pub const STD_JSON_ENCODE: &std::ffi::CStr = c"json.encode(t: JsonData, options: EncodeOptions?) -> string";
pub const STD_JSON_NULL: &std::ffi::CStr = c"json.null() -> any";
pub const STD_JSON_RAW: &std::ffi::CStr = c"json.raw(t: JsonData) -> string";
pub const STD_JSON_READFILE: &std::ffi::CStr = c"json.readfile(path: string) -> JsonData";
pub const STD_JSON_WRITEFILE: &std::ffi::CStr = c"json.writefile(path: string, data: JsonData, options: EncodeOptions?)";
pub const STD_JSON_WRITEFILE_RAW: &std::ffi::CStr = c"json.writefile_raw(path: string, data: JsonData)";

// luau
pub const STD_LUAU_BUNDLE: &std::ffi::CStr = c"luau.bundle(path: string) -> string | error";
pub const STD_LUAU_BYTECODE: &std::ffi::CStr = c"luau.bytecode(src: string) -> buffer | error";
pub const STD_LUAU_EVAL: &std::ffi::CStr = c"luau.eval(src: string, options: EvalOptions?) -> unknown | error";
pub const STD_LUAU_EVAL_UNSAFE: &std::ffi::CStr = c"luau.eval_unsafe(src: string | buffer, options: EvalOptions?) -> unknown | error";
pub const STD_LUAU_REQUIRE_RESOLVER: &std::ffi::CStr = c"luau.require_resolver() -> { resolve: (requested_path: string, requiring_file_path: string) -> { err: string, path: nil } | { path: string, err: nil }, get_aliases: (requiring_file_path: string) -> ({ [number]: LuaurcAliases }?, string?), expand_aliases: (requested_path: string, aliases_by_luaurc: { [number]: LuaurcAliases }) -> (string?, string?) }";

// net.http
pub const STD_NET_HTTP_GET: &std::ffi::CStr = c"net.http.get(options: HttpRequestWithoutBody) -> HttpResponse";
pub const STD_NET_HTTP_POST: &std::ffi::CStr = c"net.http.post(options: HttpRequestWithBody) -> HttpResponse";
pub const STD_NET_HTTP_REQUEST: &std::ffi::CStr = c"net.http.request(method: HttpMethod, options: HttpRequestWithoutBody | HttpRequestWithBody) -> HttpResponseResult";

// HttpResponse
pub const STD_NET_HTTP_HTTP_RESPONSE_EXPECT_JSON: &std::ffi::CStr = c"HttpResponse:expect_json() -> T";
pub const STD_NET_HTTP_HTTP_RESPONSE_TRY_JSON: &std::ffi::CStr = c"HttpResponse:try_json() -> T?";

// net.http.server
pub const STD_NET_HTTP_SERVER_HANDLER: &std::ffi::CStr = c"net.http.server.handler(ServeRequest) -> ServeResponse";

// net.websocket
pub const STD_NET_WEBSOCKET_CONNECT: &std::ffi::CStr = c"net.websocket.connect(url: string) -> Websocket";

// process
pub const STD_PROCESS_EXIT: &std::ffi::CStr = c"process.exit(code: number?) -> never";
pub const STD_PROCESS_RUN: &std::ffi::CStr = c"process.run(options: RunOptions) -> RunResult";
pub const STD_PROCESS_SHELL: &std::ffi::CStr = c"process.shell(command: string) -> RunResult";
pub const STD_PROCESS_SPAWN: &std::ffi::CStr = c"process.spawn(options: SpawnOptions) -> ChildProcess";

// RunResult
pub const STD_PROCESS_RUN_RESULT_UNWRAP: &std::ffi::CStr = c"RunResult:unwrap() -> string";
pub const STD_PROCESS_RUN_RESULT_UNWRAP_OR: &std::ffi::CStr = c"RunResult:unwrap_or(default: string | (result: RunResult) -> string) -> string";

// ChildProcessStream
pub const STD_PROCESS_CHILD_PROCESS_STREAM_CAPACITY: &std::ffi::CStr = c"ChildProcessStream:capacity() -> number";
pub const STD_PROCESS_CHILD_PROCESS_STREAM_FILL: &std::ffi::CStr = c"ChildProcessStream:fill(target: buffer, target_offset: number?, timeout: Duration | number?) -> number";
pub const STD_PROCESS_CHILD_PROCESS_STREAM_FILL_EXACT: &std::ffi::CStr = c"ChildProcessStream:fill_exact(count: number, target: buffer, target_offset: number?, timeout: Duration | number?) -> boolean";
pub const STD_PROCESS_CHILD_PROCESS_STREAM_ITER: &std::ffi::CStr = c"ChildProcessStream:iter(timeout: Duration | number?, write_delay_ms: number?) -> () -> string";
pub const STD_PROCESS_CHILD_PROCESS_STREAM_LEN: &std::ffi::CStr = c"ChildProcessStream:len() -> number";
pub const STD_PROCESS_CHILD_PROCESS_STREAM_LINES: &std::ffi::CStr = c"ChildProcessStream:lines(timeout: Duration | number?) -> () -> string";
pub const STD_PROCESS_CHILD_PROCESS_STREAM_READ: &std::ffi::CStr = c"ChildProcessStream:read(count: number?, timeout: Duration | number?) -> string?";
pub const STD_PROCESS_CHILD_PROCESS_STREAM_READ_EXACT: &std::ffi::CStr = c"ChildProcessStream:read_exact(count: number, timeout: Duration | number?) -> string?";
pub const STD_PROCESS_CHILD_PROCESS_STREAM_READ_TO: &std::ffi::CStr = c"ChildProcessStream:read_to(term: string, inclusive: boolean?, timeout: Duration | number?, allow_partial: boolean?) -> string?";

// ChildProcess
pub const STD_PROCESS_CHILD_PROCESS_ALIVE: &std::ffi::CStr = c"ChildProcess:alive() -> boolean";
pub const STD_PROCESS_CHILD_PROCESS_KILL: &std::ffi::CStr = c"ChildProcess:kill()";

// PipedChild
pub const STD_PROCESS_PIPED_CHILD_ALIVE: &std::ffi::CStr = c"PipedChild:alive() -> boolean";
pub const STD_PROCESS_PIPED_CHILD_KILL: &std::ffi::CStr = c"PipedChild:kill()";

// semver
pub const STD_SEMVER_DEFAULT: &std::ffi::CStr = c"semver.default() -> Semver";
pub const STD_SEMVER_FROM: &std::ffi::CStr = c"semver.from(s: string) -> Semver";

// serde.base64
pub const STD_SERDE_BASE64_DECODE: &std::ffi::CStr = c"serde.base64.decode(data: string) -> buffer";
pub const STD_SERDE_BASE64_ENCODE: &std::ffi::CStr = c"serde.base64.encode(data: string | buffer) -> string";

// serde.base64.urlsafe
pub const STD_SERDE_BASE64_URLSAFE_DECODE: &std::ffi::CStr = c"serde.base64.urlsafe.decode(data: string) -> buffer";
pub const STD_SERDE_BASE64_URLSAFE_ENCODE: &std::ffi::CStr = c"serde.base64.urlsafe.encode(data: string | buffer) -> string";

// serde.bz2
pub const STD_SERDE_BZ2_COMPRESS: &std::ffi::CStr = c"serde.bz2.compress(content: string | buffer) -> buffer";
pub const STD_SERDE_BZ2_DECOMPRESS: &std::ffi::CStr = c"serde.bz2.decompress(content: buffer, max_size: FileSize?) -> buffer";

// serde.gzip
pub const STD_SERDE_GZIP_COMPRESS: &std::ffi::CStr = c"serde.gzip.compress(content: string | buffer) -> buffer";
pub const STD_SERDE_GZIP_DECOMPRESS: &std::ffi::CStr = c"serde.gzip.decompress(content: buffer, max_size: FileSize?) -> buffer";

// serde.hex
pub const STD_SERDE_HEX_DECODE: &std::ffi::CStr = c"serde.hex.decode(encoded: string) -> buffer";
pub const STD_SERDE_HEX_ENCODE: &std::ffi::CStr = c"serde.hex.encode(data: buffer | string) -> string";

// serde.json
pub const STD_SERDE_JSON_ARRAY: &std::ffi::CStr = c"serde.json.array(t: { [number]: T }?) -> { [number]: T }";
pub const STD_SERDE_JSON_DECODE: &std::ffi::CStr = c"serde.json.decode(json: string) -> JsonData";
pub const STD_SERDE_JSON_ENCODE: &std::ffi::CStr = c"serde.json.encode(t: JsonData, options: EncodeOptions?) -> string";
pub const STD_SERDE_JSON_NULL: &std::ffi::CStr = c"serde.json.null() -> null";
pub const STD_SERDE_JSON_RAW: &std::ffi::CStr = c"serde.json.raw(t: JsonData) -> string";
pub const STD_SERDE_JSON_READFILE: &std::ffi::CStr = c"serde.json.readfile(path: string) -> JsonData";
pub const STD_SERDE_JSON_WRITEFILE: &std::ffi::CStr = c"serde.json.writefile(path: string, data: JsonData, options: EncodeOptions?)";
pub const STD_SERDE_JSON_WRITEFILE_RAW: &std::ffi::CStr = c"serde.json.writefile_raw(path: string, data: JsonData)";

// serde.lz4
pub const STD_SERDE_LZ4_COMPRESS: &std::ffi::CStr = c"serde.lz4.compress(input: string | buffer) -> buffer";
pub const STD_SERDE_LZ4_DECOMPRESS: &std::ffi::CStr = c"serde.lz4.decompress(compressed: string | buffer, expected_size: number) -> buffer";

// serde.toml
pub const STD_SERDE_TOML_DECODE: &std::ffi::CStr = c"serde.toml.decode(toml_data: string) -> TomlValue";
pub const STD_SERDE_TOML_ENCODE: &std::ffi::CStr = c"serde.toml.encode(t: TomlValue) -> string";
pub const STD_SERDE_TOML_READFILE: &std::ffi::CStr = c"serde.toml.readfile(path: string) -> TomlValue";
pub const STD_SERDE_TOML_WRITEFILE: &std::ffi::CStr = c"serde.toml.writefile(path: string, content: TomlValue)";

// serde.url
pub const STD_SERDE_URL_DECODE: &std::ffi::CStr = c"serde.url.decode(encoded: string) -> string";
pub const STD_SERDE_URL_ENCODE: &std::ffi::CStr = c"serde.url.encode(text: string) -> string";

// serde.url.binary
pub const STD_SERDE_URL_BINARY_DECODE: &std::ffi::CStr = c"serde.url.binary.decode(encoded: string) -> buffer";
pub const STD_SERDE_URL_BINARY_ENCODE: &std::ffi::CStr = c"serde.url.binary.encode(data: string | buffer) -> string";

// serde.xz
pub const STD_SERDE_XZ_COMPRESS: &std::ffi::CStr = c"serde.xz.compress(content: string | buffer) -> buffer";
pub const STD_SERDE_XZ_DECOMPRESS: &std::ffi::CStr = c"serde.xz.decompress(content: buffer, max_size: FileSize?) -> buffer";

// serde.yaml
pub const STD_SERDE_YAML_DECODE: &std::ffi::CStr = c"serde.yaml.decode(toml_data: string) -> YamlValue";
pub const STD_SERDE_YAML_ENCODE: &std::ffi::CStr = c"serde.yaml.encode(t: YamlValue) -> string";
pub const STD_SERDE_YAML_READFILE: &std::ffi::CStr = c"serde.yaml.readfile(path: string) -> YamlValue";
pub const STD_SERDE_YAML_WRITEFILE: &std::ffi::CStr = c"serde.yaml.writefile(path: string, content: YamlValue)";

// serde.zlib
pub const STD_SERDE_ZLIB_COMPRESS: &std::ffi::CStr = c"serde.zlib.compress(data: string | buffer, level: \"Default\" | \"Fast\" | \"Best\" | nil) -> buffer";
pub const STD_SERDE_ZLIB_DECOMPRESS: &std::ffi::CStr = c"serde.zlib.decompress(compressed: buffer) -> buffer";

// serde.zstd
pub const STD_SERDE_ZSTD_COMPRESS: &std::ffi::CStr = c"serde.zstd.compress(data: buffer | string, level: number?, options: ZstdOptions?) -> buffer";
pub const STD_SERDE_ZSTD_DECOMPRESS: &std::ffi::CStr = c"serde.zstd.decompress(compressed: buffer) -> buffer";

// str
pub const STD_STR_CHARS: &std::ffi::CStr = c"str.chars(s: string) -> () -> (number, string)";
pub const STD_STR_ENDS: &std::ffi::CStr = c"str.ends(s: string, ...: string) -> boolean";
pub const STD_STR_ENDSWITH: &std::ffi::CStr = c"str.endswith(s: string, suffix: string) -> boolean";
pub const STD_STR_ESCAPE: &std::ffi::CStr = c"str.escape(s: string) -> string";
pub const STD_STR_GRAPHEMES: &std::ffi::CStr = c"str.graphemes(s: string) -> () -> (number, string)";
pub const STD_STR_INDENT: &std::ffi::CStr = c"str.indent(s: string, whitespace_type: \"Tabs\" | \"Spaces\", count: number, sep: \"\n\" | \"\r\n\"?) -> string";
pub const STD_STR_LEFTPAD: &std::ffi::CStr = c"str.leftpad(s: string, width: number, pad: string?) -> string";
pub const STD_STR_LEN: &std::ffi::CStr = c"str.len(s: string) -> number";
pub const STD_STR_SLICE: &std::ffi::CStr = c"str.slice(s: string, first: number, final: number)";
pub const STD_STR_SPLIT: &std::ffi::CStr = c"str.split(s: string, ...: string) -> { [number]: string }";
pub const STD_STR_SPLITAFTER: &std::ffi::CStr = c"str.splitafter(s: string, seps: string, ...: string) -> { [number]: string }";
pub const STD_STR_SPLITAROUND: &std::ffi::CStr = c"str.splitaround(s: string, seps: string, ...: string) -> { [number]: string }";
pub const STD_STR_SPLITBEFORE: &std::ffi::CStr = c"str.splitbefore(s: string, seps: string, ...: string) -> { [number]: string }";
pub const STD_STR_SPLITLINES: &std::ffi::CStr = c"str.splitlines(s: string, trim_trailing_whitespace: boolean?) -> { [number]: string }";
pub const STD_STR_STARTS: &std::ffi::CStr = c"str.starts(s: string, ...: string) -> boolean";
pub const STD_STR_STARTSWITH: &std::ffi::CStr = c"str.startswith(s: string, prefix: string) -> boolean";
pub const STD_STR_TRIM: &std::ffi::CStr = c"str.trim(s: string, ...: string) -> string";
pub const STD_STR_TRIMBACK: &std::ffi::CStr = c"str.trimback(s: string, ...: string) -> string";
pub const STD_STR_TRIMFRONT: &std::ffi::CStr = c"str.trimfront(s: string, ...: string) -> string";
pub const STD_STR_UNESCAPE: &std::ffi::CStr = c"str.unescape(s: string) -> string";
pub const STD_STR_UNINDENT: &std::ffi::CStr = c"str.unindent(s: string, whitespace_type: \"Tabs\" | \"Spaces\", count: number, sep: \"\n\" | \"\r\n\"?) -> string";
pub const STD_STR_WIDTH: &std::ffi::CStr = c"str.width(s: string) -> number";

// terminal.cursor
pub const STD_TERMINAL_CURSOR_COLUMN: &std::ffi::CStr = c"terminal.cursor.column(c: number) -> TerminalAction";
pub const STD_TERMINAL_CURSOR_DOWN: &std::ffi::CStr = c"terminal.cursor.down(r: number) -> TerminalAction";
pub const STD_TERMINAL_CURSOR_HIDE: &std::ffi::CStr = c"terminal.cursor.hide() -> TerminalAction";
pub const STD_TERMINAL_CURSOR_LEFT: &std::ffi::CStr = c"terminal.cursor.left(c: number) -> TerminalAction";
pub const STD_TERMINAL_CURSOR_NEXTLINE: &std::ffi::CStr = c"terminal.cursor.nextline(n: number?) -> TerminalAction";
pub const STD_TERMINAL_CURSOR_POSITION: &std::ffi::CStr = c"terminal.cursor.position() -> vector";
pub const STD_TERMINAL_CURSOR_PREVLINE: &std::ffi::CStr = c"terminal.cursor.prevline(n: number?) -> TerminalAction";
pub const STD_TERMINAL_CURSOR_RESTORE: &std::ffi::CStr = c"terminal.cursor.restore() -> TerminalAction";
pub const STD_TERMINAL_CURSOR_RIGHT: &std::ffi::CStr = c"terminal.cursor.right(c: number) -> TerminalAction";
pub const STD_TERMINAL_CURSOR_ROW: &std::ffi::CStr = c"terminal.cursor.row(r: number) -> TerminalAction";
pub const STD_TERMINAL_CURSOR_SAVE: &std::ffi::CStr = c"terminal.cursor.save() -> TerminalAction";
pub const STD_TERMINAL_CURSOR_SHOW: &std::ffi::CStr = c"terminal.cursor.show() -> TerminalAction";
pub const STD_TERMINAL_CURSOR_STYLE: &std::ffi::CStr = c"terminal.cursor.style(mode: CursorStyle) -> TerminalAction";
pub const STD_TERMINAL_CURSOR_UP: &std::ffi::CStr = c"terminal.cursor.up(r: number) -> TerminalAction";

// terminal
pub const STD_TERMINAL_BACKGROUND: &std::ffi::CStr = c"terminal.background() -> vector?";
pub const STD_TERMINAL_CLEAR: &std::ffi::CStr = c"terminal.clear(mode: ClearMode?) -> TerminalAction";
pub const STD_TERMINAL_EVENTS: &std::ffi::CStr = c"terminal.events(poll: Duration) -> () -> TerminalEvent";
pub const STD_TERMINAL_EXECUTE: &std::ffi::CStr = c"terminal.execute()";
pub const STD_TERMINAL_LINEWRAP: &std::ffi::CStr = c"terminal.linewrap(enabled: boolean) -> TerminalAction";
pub const STD_TERMINAL_RESET: &std::ffi::CStr = c"terminal.reset()";
pub const STD_TERMINAL_SCROLL: &std::ffi::CStr = c"terminal.scroll(lines: number) -> TerminalAction";
pub const STD_TERMINAL_SIZE: &std::ffi::CStr = c"terminal.size() -> vector";
pub const STD_TERMINAL_SWITCH: &std::ffi::CStr = c"terminal.switch(screen: \"Main\" | \"Alternate\") -> TerminalAction";
pub const STD_TERMINAL_TITLE: &std::ffi::CStr = c"terminal.title(title: string) -> TerminalAction";
pub const STD_TERMINAL_TTY: &std::ffi::CStr = c"terminal.tty(stream: \"Stdout\" | \"Stderr\" | \"Stdin\" | nil) -> boolean";
pub const STD_TERMINAL_WRITE: &std::ffi::CStr = c"terminal.write(content: string) -> TerminalAction";

// terminal.rawmode
pub const STD_TERMINAL_RAWMODE_DISABLE: &std::ffi::CStr = c"terminal.rawmode.disable()";
pub const STD_TERMINAL_RAWMODE_ENABLE: &std::ffi::CStr = c"terminal.rawmode.enable()";
pub const STD_TERMINAL_RAWMODE_ENABLED: &std::ffi::CStr = c"terminal.rawmode.enabled() -> boolean";

// terminal.interrupt
pub const STD_TERMINAL_INTERRUPT_CHECK: &std::ffi::CStr = c"terminal.interrupt.check(event: TerminalEvent) -> interrupt?";
pub const STD_TERMINAL_INTERRUPT_EOF: &std::ffi::CStr = c"terminal.interrupt.eof() -> interrupt";
pub const STD_TERMINAL_INTERRUPT_SIGINT: &std::ffi::CStr = c"terminal.interrupt.sigint() -> interrupt";

// terminal.capture
pub const STD_TERMINAL_CAPTURE_FOCUS: &std::ffi::CStr = c"terminal.capture.focus(enabled: boolean)";
pub const STD_TERMINAL_CAPTURE_MOUSE: &std::ffi::CStr = c"terminal.capture.mouse(enabled: boolean)";
pub const STD_TERMINAL_CAPTURE_PASTE: &std::ffi::CStr = c"terminal.capture.paste(enabled: boolean)";

// thread
pub const STD_THREAD_PARALLELISM: &std::ffi::CStr = c"thread.parallelism() -> number";
pub const STD_THREAD_SLEEP: &std::ffi::CStr = c"thread.sleep(milliseconds: number) -> true";
pub const STD_THREAD_SPAWN: &std::ffi::CStr = c"thread.spawn(spawn_options: ThreadSpawnOptions) -> ThreadHandle";

// ThreadHandle
pub const STD_THREAD_THREAD_HANDLE_JOIN: &std::ffi::CStr = c"ThreadHandle:join()";
pub const STD_THREAD_THREAD_HANDLE_READ: &std::ffi::CStr = c"ThreadHandle:read() -> JsonSerializableTable | nil | string | nil";
pub const STD_THREAD_THREAD_HANDLE_READ_AWAIT: &std::ffi::CStr = c"ThreadHandle:read_await() -> JsonSerializableTable | string";
pub const STD_THREAD_THREAD_HANDLE_READBYTES: &std::ffi::CStr = c"ThreadHandle:readbytes() -> buffer?";
pub const STD_THREAD_THREAD_HANDLE_READBYTES_AWAIT: &std::ffi::CStr = c"ThreadHandle:readbytes_await() -> buffer";
pub const STD_THREAD_THREAD_HANDLE_SEND: &std::ffi::CStr = c"ThreadHandle:send(data: JsonSerializableTable | string)";
pub const STD_THREAD_THREAD_HANDLE_SENDBYTES: &std::ffi::CStr = c"ThreadHandle:sendbytes(data: buffer)";
pub const STD_THREAD_THREAD_HANDLE_TRY_SEND: &std::ffi::CStr = c"ThreadHandle:try_send(data: JsonSerializableTable | string) -> (boolean, \"Sent\" | \"Disconnected\" | \"Full\")";
pub const STD_THREAD_THREAD_HANDLE_TRY_SENDBYTES: &std::ffi::CStr = c"ThreadHandle:try_sendbytes(data: buffer) -> (boolean, \"Sent\" | \"Disconnected\" | \"Full\")";

// time.datetime
pub const STD_TIME_DATETIME_DAYS: &std::ffi::CStr = c"time.datetime.days(number) -> TimeSpan";
pub const STD_TIME_DATETIME_FROM: &std::ffi::CStr = c"time.datetime.from(timestamp: number, timezone: IanaTimezone, nanos: number?) -> DateTime";
pub const STD_TIME_DATETIME_HOURS: &std::ffi::CStr = c"time.datetime.hours(number) -> TimeSpan";
pub const STD_TIME_DATETIME_MILLISECONDS: &std::ffi::CStr = c"time.datetime.milliseconds(number) -> TimeSpan";
pub const STD_TIME_DATETIME_MINUTES: &std::ffi::CStr = c"time.datetime.minutes(number) -> TimeSpan";
pub const STD_TIME_DATETIME_MONTHS: &std::ffi::CStr = c"time.datetime.months(number, relative_to: DateTime?) -> TimeSpan";
pub const STD_TIME_DATETIME_NOW: &std::ffi::CStr = c"time.datetime.now() -> DateTime";
pub const STD_TIME_DATETIME_PARSE: &std::ffi::CStr = c"time.datetime.parse(source: string, format: string | CommonFormats, timezone: IanaTimezone) -> DateTime";
pub const STD_TIME_DATETIME_SECONDS: &std::ffi::CStr = c"time.datetime.seconds(number) -> TimeSpan";
pub const STD_TIME_DATETIME_YEARS: &std::ffi::CStr = c"time.datetime.years(number, relative_to: DateTime?) -> TimeSpan";

// time
pub const STD_TIME_DAYS: &std::ffi::CStr = c"time.days(d: number) -> Duration";
pub const STD_TIME_HOURS: &std::ffi::CStr = c"time.hours(h: number) -> Duration";
pub const STD_TIME_MICROSECONDS: &std::ffi::CStr = c"time.microseconds(us: number) -> Duration";
pub const STD_TIME_MILLISECONDS: &std::ffi::CStr = c"time.milliseconds(ms: number) -> Duration";
pub const STD_TIME_MINUTES: &std::ffi::CStr = c"time.minutes(m: number) -> Duration";
pub const STD_TIME_MONTHS: &std::ffi::CStr = c"time.months(months: number) -> Duration";
pub const STD_TIME_NANOSECONDS: &std::ffi::CStr = c"time.nanoseconds(n: number) -> Duration";
pub const STD_TIME_SECONDS: &std::ffi::CStr = c"time.seconds(s: number) -> Duration";
pub const STD_TIME_WAIT: &std::ffi::CStr = c"time.wait(duration: Duration | number) -> true";
pub const STD_TIME_YEARS: &std::ffi::CStr = c"time.years(y: number) -> Duration";
